parser_1 = argparse.ArgumentParser()
# group = parser_1.add_argument_group('authentication')
# group.add_argument('--user', action="store")
# group.add_argument('--password', action="store")
# parser_1.add_argument('--push', action="store")
# print(parser_1.parse_args(['-h']))